# Compiler Construction 2013 
# Computer Laboratory 
# University of Cambridge 
# Timothy G. Griffin (tgg22@cam.ac.uk) 


# assumes gcc is installed! 
FLAGS = -pedantic -Wall -ansi
CC = gcc

all:
	$(CC) $(FLAGS) vrm.c main.c -o vrm0 

clean:
	rm -f vrm0 